import React, { useState } from "react";
import axios from "axios";
import { jsPDF } from "jspdf";
import Chatbot from "./Chatbot";
import "./App.css";

const tumorDetails = {
  "Glioma Tumor": {
    description:
      "Glioma is a type of tumor that occurs in the brain and spinal cord. Immediate consultation recommended.",
    recommendation: "Please consult a Neurologist for an MRI contrast scan.",
  },
  "Meningioma Tumor": {
    description:
      "A meningioma is a tumor that arises from the meninges. Often benign but needs monitoring.",
    recommendation: "Schedule an appointment with a Neurosurgeon.",
  },
  "Pituitary Tumor": {
    description:
      "Abnormal growths in your pituitary gland affecting hormone levels.",
    recommendation: "Consult an Endocrinologist and a Neurosurgeon.",
  },
  "No Tumor": {
    description: "No abnormalities detected. Maintain a healthy lifestyle.",
    recommendation: "Routine checkups are advised.",
  },
};

function App() {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleFileChange = (event) => {
    const selectedFile = event.target.files[0];
    if (selectedFile) {
      setFile(selectedFile);
      setPreview(URL.createObjectURL(selectedFile));
      setResult(null);
    }
  };

  const handleUpload = async () => {
    if (!file) return alert("Select an image!");
    const formData = new FormData();
    formData.append("image", file);
    setLoading(true);

    try {
      const response = await axios.post(
        "https://Kalana.pythonanywhere.com/predict",
        formData
      );
      setResult(response.data);
    } catch (error) {
      console.error(error);
      alert("Backend connection failed!");
    } finally {
      setLoading(false);
    }
  };

  // PDF Report Generation
  const generatePDF = () => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(41, 128, 185); // Blue color
    doc.text("NeuroVision AI - Medical Report", 20, 20);

    // Line separator
    doc.setLineWidth(0.5);
    doc.line(20, 25, 190, 25);

    // Date
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Date: ${new Date().toLocaleString()}`, 20, 35);

    // Results Section
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Diagnostic Result", 20, 50);

    doc.setFontSize(14);
    if (result.status === "danger") {
      doc.setTextColor(214, 48, 49); // Red for danger
    } else {
      doc.setTextColor(39, 174, 96); // Green for safe
    }
    doc.text(`Condition: ${result.result}`, 20, 60);

    doc.setTextColor(0);
    doc.text(`Confidence Score: ${result.confidence}`, 20, 70);

    // Description Box
    doc.setFontSize(12);
    doc.text("Analysis:", 20, 90);

    const splitDesc = doc.splitTextToSize(
      tumorDetails[result.result]?.description || "",
      170
    );
    doc.text(splitDesc, 20, 100);

    // Recommendation
    doc.setFontSize(12);
    doc.setTextColor(214, 48, 49);
    doc.text("Recommendation:", 20, 130);

    const splitRec = doc.splitTextToSize(
      tumorDetails[result.result]?.recommendation || "",
      170
    );
    doc.setTextColor(0);
    doc.text(splitRec, 20, 140);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by NeuroVision AI System", 20, 280);

    // Save PDF
    doc.save("NeuroVision_Report.pdf");
  };

  return (
    <div className="main-container">
      <div className="dashboard-card">
        {/* Header Section */}
        <div className="header">
          <h1>🧠 NeuroVision AI</h1>
          <p className="subtitle">Advanced Brain Tumor Detection System</p>
        </div>

        {/* Upload Section */}
        {!preview && (
          <div
            className="upload-area"
            onClick={() => document.getElementById("fileInput").click()}
          >
            <input
              type="file"
              id="fileInput"
              onChange={handleFileChange}
              hidden
            />
            <span className="upload-icon">📂</span>
            <p className="upload-label">Click to Upload MRI Scan</p>
          </div>
        )}

        {/* Display Section */}
        {preview && (
          <div
            className={`content-grid ${result ? "with-result" : "centered"}`}
          >
            {/* Left Side: Image */}
            <div className="image-section">
              <div className="image-preview-box">
                <img src={preview} alt="Scan" className="preview-img" />
                {!result && <div className="scan-line"></div>}
              </div>

              {/* Change Image Button */}
              {!loading && (
                <button
                  onClick={() => {
                    setPreview(null);
                    setFile(null);
                    setResult(null);
                  }}
                  style={{
                    marginTop: "10px",
                    background: "none",
                    border: "none",
                    color: "#636e72",
                    cursor: "pointer",
                    textDecoration: "underline",
                  }}
                >
                  Upload Different Scan
                </button>
              )}

              {/* Analyze Button */}
              {!result && (
                <button
                  className="analyze-btn"
                  onClick={handleUpload}
                  disabled={loading}
                >
                  {loading ? "Scanning..." : "🔍 Analyze Now"}
                </button>
              )}
            </div>

            {/* Right Side: Result */}
            {result && (
              <div className={`result-panel ${result.status}`}>
                <span className={`badge ${result.status}`}>
                  {result.status === "danger" ? "Attention Required" : "Normal"}
                </span>
                <h2 className="diagnosis-title">{result.result}</h2>

                <p
                  style={{
                    fontSize: "0.8rem",
                    color: "#888",
                    marginBottom: "5px",
                  }}
                >
                  Confidence Score
                </p>
                <div className="confidence-bar">
                  <div
                    className="confidence-fill"
                    style={{ width: result.confidence }}
                  ></div>
                </div>
                <p style={{ textAlign: "right", fontWeight: "bold" }}>
                  {result.confidence}
                </p>

                <div className="info-text">
                  <p>
                    <strong>📋 Analysis:</strong>{" "}
                    {tumorDetails[result.result]?.description}
                  </p>
                  <p
                    style={{
                      color: result.status === "danger" ? "#d63031" : "#00b894",
                      fontWeight: "bold",
                      marginTop: "10px",
                    }}
                  >
                    💡 {tumorDetails[result.result]?.recommendation}
                  </p>
                </div>

                <button onClick={generatePDF} className="download-btn">
                  📄 Download Medical Report
                </button>
              </div>
            )}
          </div>
        )}
      </div>

      <Chatbot result={result} />
    </div>
  );
}

export default App;
